language: c
compiler: clang
script:
    - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DVIEWER=On .. && cmake --build . && ctest
addons:
    apt:
        packages:
            - libglew-dev
            - libsdl2-dev
            - check
